// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Connection;

namespace Server.Migrations
{
    [DbContext(typeof(idszContext))]
    [Migration("20190813065558_bookandauthor1")]
    partial class bookandauthor1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sourcer.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "East"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "West"
                        });
                });

            modelBuilder.Entity("Sourcer.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<string>("BookName");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AuthorId = 1,
                            BookName = "Slience"
                        },
                        new
                        {
                            Id = 102,
                            AuthorId = 1,
                            BookName = "Skill"
                        },
                        new
                        {
                            Id = 103,
                            AuthorId = 2,
                            BookName = "Scare"
                        });
                });

            modelBuilder.Entity("Sourcer.Book", b =>
                {
                    b.HasOne("Sourcer.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
